substitutions:
  name: "moon-display"
  friendly_name: Moon Display

  Outlines: "0" # Setting to 0 will disable all Outlines
#---------------------------------------------------------------------------------------------------
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.9.0
  name_add_mac_suffix: false
  project:
    name: edickens.moon_display
    version: '1.0'
  on_boot: 
    priority: -100
    then:
      - light.turn_on: 
          id: backlight
          brightness: 75%
      - script.execute: rainbow_on
      - script.execute: init_brightness
#---------------------------------------------------------------------------------------------------
esp32:
  variant: esp32c6
  framework:
    type: esp-idf
#---------------------------------------------------------------------------------------------------
# Enable logging
logger:
  level: DEBUG
#---------------------------------------------------------------------------------------------------
# Enable Home Assistant API
api:
  encryption: 
    key: !secret haapi_key
#---------------------------------------------------------------------------------------------------
# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password
#---------------------------------------------------------------------------------------------------
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: off
#---------------------------------------------------------------------------------------------------
time:
  - platform: homeassistant
    id: esptime
    on_time_sync:
    - lvgl.label.update:
        id: display_time
        text: !lambda return id(HATime).state;
    - lvgl.label.update:
        id: display_date
        text: !lambda return id(HADate).state;
    on_time:
      - hours: 10,12,14,16,6
        minutes: 0
        seconds: 0
        then:
          - switch.turn_on: switch_antiburn
      - hours: 10,12,14,16,6
        minutes: 15
        seconds: 0
        then:
          - switch.turn_off: switch_antiburn
#---------------------------------------------------------------------------------------------------
spi:
  - id: lcd
    clk_pin:
      number: GPIO7
    mosi_pin:
      number: GPIO6
#---------------------------------------------------------------------------------------------------
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP
      update_interval: 1h
    ssid:
      name: ${friendly_name} SSID
      update_interval: 1h
    mac_address:
      name: ${friendly_name} Mac
#--------------------------------------
  - platform: homeassistant
    id: HATime
    entity_id: sensor.12_hour_time
    device_class: timestamp
    internal: true
    on_value:
      - lvgl.label.update:
          id: display_time
          text: !lambda return id(HATime).state;
#--------------------------------------
  - platform: homeassistant
    id: HADate
    entity_id: sensor.date
    device_class: timestamp
    internal: true
    on_value:
      - lvgl.label.update:
          id: display_date
          text: !lambda return id(HADate).state;
#---------------------------------------------------------------------------------------------------
sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    id: encoder_steps
    pin_a: GPIO2 # Replace with your CLK/A pin
    pin_b: GPIO1 # Replace with your DT/B pin
    resolution: 1 # Number of steps per click
    # If the values go in the wrong direction, swap pin_a and pin_b

  - platform: template
    name: "Moon Brightness"
    id: moon_brightness_sensor
    update_interval: never
    internal: True
    lambda: |-
      // Access the light's internal state object and get the brightness.
      // Returns a float between 0.0 and 1.0.
      float m_brightness = id(LED_Array).current_values.get_brightness();

      // Optionally, convert to a percentage (0-100) and return it.
      return m_brightness * 100.0;
    on_value:
      then:
        - lvgl.slider.update:
            id: moon_brightness_slider
            value: !lambda 'return x;' # x is the value from the lambda


#  - platform: homeassistant
#    id: moon_brightness_sensor
#    entity_id: light.moon_display_moon_display_led_array
#    attribute: brightness
#    internal: true
#    on_value:
#      then:
#        - lvgl.slider.update:
#            id: moon_brightness_slider
#            value: !lambda 'return x / 2.55;' # x (0-255) is the value from the sensor. Needs to be scaled to 0-100.

  - platform: template
    name: "Display Brightness"
    id: display_brightness_sensor
    update_interval: never
    internal: True
    lambda: |-
      // Access the light's internal state object and get the brightness.
      // Returns a float between 0.0 and 1.0.
      float d_brightness = id(backlight).current_values.get_brightness();

      // Optionally, convert to a percentage (0-100) and return it.
      return d_brightness * 100.0;
    on_value:
      then:
        - lvgl.slider.update:
            id: display_brightness_slider
            value: !lambda 'return x;' # x is the value from the lambda


#  - platform: homeassistant
#    id: backlight_brightness_sensor
#    entity_id: light.moon_display_lcd_backlight
#    attribute: brightness
#    internal: true
#    on_value:
#      then:
#        - lvgl.slider.update:
#            id: display_brightness_slider
#            value: !lambda 'return x / 2.55;' # x (0-255) is the value from the sensor. Needs to be scaled to 0-100.

#---------------------------------------------------------------------------------------------------
binary_sensor:
  - platform: gpio
    id: encoder_button
    pin:
      number: GPIO3 # Replace with your SW pin
      inverted: True
      mode: 
        input: true # Ensure the pin mode is set correctly
        pullup: true # Use internal pullup resistor
    name: "Encoder Button"
    on_double_click: 
      then:
        lvgl.page.next
    on_click: 
      min_length: 400ms
      max_length: 10s
      then:
        - light.toggle: LED_Array
        - light.toggle: backlight
#---------------------------------------------------------------------------------------------------
switch:
  - platform: restart
    name: "${friendly_name} Restart"
#-------------------------------------------------------
  - platform: template
    name: Antiburn
    id: switch_antiburn
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - logger.log: "${friendly_name} Starting Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - logger.log: "${friendly_name} Stopping Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
            - lvgl.pause:
#---------------------------------------------------------------------------------------------------
# Backlight control
output:
  - platform: ledc
    pin: GPIO22
    id: backlight_output
    frequency: 5000 Hz
#---------------------------------------------------------------------------------------------------
light:
  - platform: monochromatic
    output: backlight_output
    id: backlight
    name: "LCD Backlight"
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 1s
#--------------------------------------
  - platform: esp32_rmt_led_strip
    id: LED_Array
    chipset: ws2812
    pin: GPIO0
    rgb_order: GRB
    num_leds: 7
    name: "${friendly_name} LED Array"
    effects: 
      - addressable_flicker: 
          name: Flicker
          update_interval: 16ms
          intensity: 25%
      - addressable_rainbow:
          name: Rainbow
    on_turn_on: 
      then:
        - script.execute: rainbow_on
#---------------------------------------------------------------------------------------------------
script:
  - id: rainbow_on
    then:
    - light.turn_on:
        id: LED_Array
        brightness: 80% # Set the brightness and colors/temperature as desired for the effect
        effect: "Rainbow" # Use the exact name of the defined effect

  - id: init_brightness
    then:
      - lambda: |-
          float m_brightness = id(LED_Array).current_values.get_brightness();
          id(moon_brightness_sensor).publish_state(m_brightness * 100.0);
          float d_brightness = id(backlight).current_values.get_brightness();
          id(display_brightness_sensor).publish_state(d_brightness * 100.0);
#---------------------------------------------------------------------------------------------------
display:
  - platform: ili9xxx
    id: moon_display
    model: ST7789V
    spi_id: lcd
    color_palette: 8BIT
    cs_pin: 
      number: GPIO14
    dc_pin: 
      number: GPIO15
      ignore_strapping_warning: true
    reset_pin: 
      number: GPIO21
    invert_colors: true
    update_interval: never
    auto_clear_enabled: false
    show_test_card: False
    dimensions: 
      height: 172 #Landscape
      width: 320 #Landscape
      offset_width: 0 #Landscape
      offset_height: 34 #Landscape
#      height: 320 #Portrait
#      width: 172 #Portrait
#      offset_width: 34 #Portrait
#      offset_height: 0 #Portrait
    transform: 
      mirror_x: False #Landscape
      mirror_y: True #Landscape
      swap_xy: True #Landscape
#      mirror_x: False #Portrait
#      mirror_y: False #Portrait
#      swap_xy: False #Portrait
#---------------------------------------------------------------------------------------------------
lvgl:
#  log_level: DEBUG
  displays:
    - moon_display
  encoders:
    enter_button: encoder_button
    sensor: encoder_steps
#--------------------------------------
  style_definitions:
    - id: mystyle
      text_font: concert_48
      text_color: 0x2F8CD8
      bg_color: 0x000000
      align: CENTER
      text_align: CENTER
#--------------------------------------
  pages:
    - id: time_page
      bg_color: 0x000000
      widgets:
        - button:
            bg_color: 0x000000
            width: 80%
            height: 45%
            align: top_mid
            focused: 
              bg_color: 0x111111
            widgets:
              - label:
                  id: display_time
                  text: "--:--"
                  styles: mystyle
                  outline_width: ${Outlines}
                  outline_color: 0x00FF00
        - button:
            bg_color: 0x000000
            width: 80%
            height: 45%
            align: bottom_mid
            focused: 
              bg_color: 0x111111
            widgets:
              - label:
                  id: display_date
                  text: "----/--/--"
                  styles: mystyle
                  outline_width: ${Outlines}
                  outline_color: 0x00FF00
#--------------------------------------
    - id: brightness_page
      bg_color: 0x000000
      layout:
        type: grid
        grid_columns: [FR(75),FR(25)]
        grid_rows: [FR(1),FR(1),FR(1),FR(1)]
      widgets:
        - label:
            grid_cell_column_pos: 0
            grid_cell_row_pos: 0
            grid_cell_column_span: 2
            grid_cell_x_align: STRETCH
            grid_cell_y_align: STRETCH
            text_align: CENTER
            text: "Moon Brightness"
            text_font: montserrat_20
            text_color: 0xFFFFFF
            outline_width: ${Outlines}
            outline_color: 0x00FF00
        - slider:
            id: moon_brightness_slider
            grid_cell_column_pos: 0
            grid_cell_row_pos: 1
            outline_width: ${Outlines}
            outline_color: 0x00FF00
            grid_cell_x_align: STRETCH
            grid_cell_y_align: CENTER
            text_align: CENTER
            bg_color: 0x555555
            min_value: 0
            max_value: 100
            focused:
              bg_color: 0x00FF00
            knob:
              focused:
                bg_color: 0x00FF00
            on_value:
              - light.turn_on:
                  id: LED_Array
                  brightness: !lambda |-
                    return x / 100.0; // Output value must be 0.0 to 1.0
              - lvgl.label.update:
                  id: moon_brightness_label
                  text:
                    format: "%.0f%%"
                    args: [ x ]
        - label:
            id: moon_brightness_label
            grid_cell_column_pos: 1
            grid_cell_row_pos: 1
            grid_cell_x_align: STRETCH
            grid_cell_y_align: STRETCH
            text_align: CENTER
            outline_width: ${Outlines}
            outline_color: 0x00FF00
            text: "XX%%"
            text_font: montserrat_20
            text_color: 0xFFFFFF

        - label:
            grid_cell_column_pos: 0
            grid_cell_row_pos: 2
            grid_cell_column_span: 2
            grid_cell_x_align: STRETCH
            grid_cell_y_align: STRETCH
            text_align: CENTER
            outline_width: ${Outlines}
            outline_color: 0x00FF00
            text: "Display Brightness"
            text_font: montserrat_20
            text_color: 0xFFFFFF
        - slider:
            id: display_brightness_slider
            grid_cell_column_pos: 0
            grid_cell_row_pos: 3
            outline_width: ${Outlines}
            outline_color: 0x00FF00
            grid_cell_x_align: STRETCH
            grid_cell_y_align: CENTER
            text_align: CENTER
            bg_color: 0x555555
            min_value: 0
            max_value: 100
            focused:
              bg_color: 0x00FF00
            knob:
              focused:
                bg_color: 0x00FF00
            on_value:
              - light.turn_on:
                  id: backlight
                  brightness: !lambda |-
                    return x / 100.0; // Output value must be 0.0 to 1.0
              - lvgl.label.update:
                  id: display_brightness_label
                  text:
                    format: "%.0f%%"
                    args: [ x ]
        - label:
            id: display_brightness_label
            grid_cell_column_pos: 1
            grid_cell_row_pos: 3
            grid_cell_x_align: STRETCH
            grid_cell_y_align: STRETCH
            text_align: CENTER
            outline_width: ${Outlines}
            outline_color: 0x00FF00
            text: "XX%%"
            text_font: montserrat_20
            text_color: 0xFFFFFF
#---------------------------------------------------------------------------------------------------
font:
  - file: "gfonts://Concert One"
    id: concert_48
    size: 48
    bpp: 4
#-------------------------------------------------------

#---------------------------------------------------------------------------------------------------
