substitutions:
  name: "moon-display"
  friendly_name: Moon Display

  Outlines: "0" # Setting to 0 will disable all Outlines
#---------------------------------------------------------------------------------------------------
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.9.0
  name_add_mac_suffix: false
  project:
    name: edickens.moon_display
    version: '1.0'
  on_boot: 
    priority: -100
    then:
      - light.turn_on: 
          id: backlight
          brightness: 75%
      - script.execute: rainbow_on
#---------------------------------------------------------------------------------------------------
esp32:
  variant: esp32c6
  framework:
    type: esp-idf
#---------------------------------------------------------------------------------------------------
# Enable logging
logger:
  level: DEBUG
#---------------------------------------------------------------------------------------------------
# Enable Home Assistant API
api:
  encryption: 
    key: !secret haapi_key
#---------------------------------------------------------------------------------------------------
# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password
#---------------------------------------------------------------------------------------------------
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: off
#---------------------------------------------------------------------------------------------------
time:
  - platform: homeassistant
    id: esptime
    on_time_sync:
    - lvgl.label.update:
        id: display_time
        text: !lambda return id(HATime).state;
    - lvgl.label.update:
        id: display_date
        text: !lambda return id(HADate).state;
#---------------------------------------------------------------------------------------------------
spi:
  - id: lcd
    clk_pin:
      number: GPIO7
    mosi_pin:
      number: GPIO6
#---------------------------------------------------------------------------------------------------
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP
      update_interval: 1h
    ssid:
      name: ${friendly_name} SSID
      update_interval: 1h
    mac_address:
      name: ${friendly_name} Mac
#--------------------------------------
  - platform: homeassistant
    id: HATime
    entity_id: sensor.12_hour_time
    device_class: timestamp
    internal: true
    on_value:
      - lvgl.label.update:
          id: display_time
          text: !lambda return id(HATime).state;
#--------------------------------------
  - platform: homeassistant
    id: HADate
    entity_id: sensor.date
    device_class: timestamp
    internal: true
    on_value:
      - lvgl.label.update:
          id: display_date
          text: !lambda return id(HADate).state;
#---------------------------------------------------------------------------------------------------
sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    id: encoder_steps
    pin_a: GPIO1 # Replace with your CLK/A pin
    pin_b: GPIO2 # Replace with your DT/B pin
    resolution: 1 # Number of steps per click
    # If the values go in the wrong direction, swap pin_a and pin_b
#---------------------------------------------------------------------------------------------------
binary_sensor:
  - platform: gpio
    id: encoder_button
    pin:
      number: GPIO3 # Replace with your SW pin
      inverted: True
      mode: 
        input: true # Ensure the pin mode is set correctly
        pullup: true # Use internal pullup resistor
    name: "Encoder Button"
#---------------------------------------------------------------------------------------------------
switch:
  - platform: restart
    name: "${friendly_name} Restart"
#---------------------------------------------------------------------------------------------------
# Backlight control
output:
  - platform: ledc
    pin: GPIO22
    id: backlight_output
    frequency: 5000 Hz
#---------------------------------------------------------------------------------------------------
light:
  - platform: monochromatic
    output: backlight_output
    id: backlight
    name: "LCD Backlight"
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 1s
#--------------------------------------
  - platform: esp32_rmt_led_strip
    id: LED_Array
    chipset: ws2812
    pin: GPIO0
    rgb_order: GRB
    num_leds: 7
    name: "${friendly_name} LED Array"
    effects: 
      - addressable_flicker: 
          name: Flicker
          update_interval: 16ms
          intensity: 25%
      - addressable_rainbow:
          name: Rainbow
    on_turn_on: 
      then:
        - script.execute: rainbow_on
#---------------------------------------------------------------------------------------------------
script:
  - id: rainbow_on
    then:
    - light.turn_on:
        id: LED_Array
        brightness: 80% # Set the brightness and colors/temperature as desired for the effect
        effect: "Rainbow" # Use the exact name of the defined effect
#---------------------------------------------------------------------------------------------------
display:
  - platform: ili9xxx
    id: moon_display
    model: ST7789V
    spi_id: lcd
    color_palette: 8BIT
    cs_pin: 
      number: GPIO14
    dc_pin: 
      number: GPIO15
      ignore_strapping_warning: true
    reset_pin: 
      number: GPIO21
    invert_colors: true
    update_interval: never
    auto_clear_enabled: false
    show_test_card: False
    dimensions: 
      height: 172 #Landscape
      width: 320 #Landscape
      offset_width: 0 #Landscape
      offset_height: 34 #Landscape
#      height: 320 #Portrait
#      width: 172 #Portrait
#      offset_width: 34 #Portrait
#      offset_height: 0 #Portrait
    transform: 
      mirror_x: False #Landscape
      mirror_y: True #Landscape
      swap_xy: True #Landscape
#      mirror_x: False #Portrait
#      mirror_y: False #Portrait
#      swap_xy: False #Portrait
#---------------------------------------------------------------------------------------------------
lvgl:
  log_level: DEBUG
  displays:
    - moon_display
  encoders:
    enter_button: encoder_button
    sensor: encoder_steps
#--------------------------------------
  style_definitions:
    - id: mystyle
      text_font: concert_48
      text_color: 0x2F8CD8
      bg_color: 0x000000
      align: CENTER
      text_align: CENTER
      height: 167 #Landscape
      width: 315 #Landscape
#      height: 320 #Portrait
#      width: 172 #Portrait
#--------------------------------------
  pages:
    - id: main_page
      bg_color: 0x000000
      widgets:
        - label:
            id: display_time
            text: "--:--"
            styles: mystyle
            height: 50%
            align: top_mid
            outline_width: ${Outlines}
            outline_color: 0x00FF00
        - label:
            id: display_date
            text: "----/--/--"
            styles: mystyle
            height: 50%
            align: bottom_mid
            outline_width: ${Outlines}
            outline_color: 0x00FF00
#--------------------------------------
    - id: brightness_page
      bg_color: 0x000000
      widgets:
        - label:
            id: label_brightness
            text: "Brightness"
            styles: mystyle
            outline_width: ${Outlines}
            outline_color: 0x00FF00
#--------------------------------------
    - id: color_page
      bg_color: 0x000000
      widgets:
        - label:
            id: label_color
            text: "Color"
            styles: mystyle
            outline_width: ${Outlines}
            outline_color: 0x00FF00
#---------------------------------------------------------------------------------------------------
font:
  - file: "gfonts://Concert One"
    id: concert_48
    size: 48
    bpp: 4
#-------------------------------------------------------

#---------------------------------------------------------------------------------------------------
